[project]
id = "0207ce4a-c788-4f28-a8b6-3dfa86ce4990"
slug = "test"
name = "test"
created_at = "2026-02-05T13:15:01.956945300Z"

[indexing]
include = []
exclude = []

[embedding]
provider = "gemini"
model = "gemini-embedding-001"
dimension = 768
